[manager]
prepend_keymap = [
 { on = [ "f" ], run = "plugin easyjump", desc = "easyjump" },
 { on = [ "M" ], run = "plugin mount", desc = "mount" },
 { on = [ "g", "l" ], run = "plugin lazygit", desc = "run lazygit" },
]
