[mgr]
ratio = [1, 4, 3]
linemode = "size"
show_hidden = true

[opener]
edit = [{ run = '$EDITOR "$@"', block = true }]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
